LABEL Arch Linux
  LINUX /Image
  FDT /rk3326-r36ultra-nodisp.dtb
  APPEND root=/dev/mmcblk0p2 rootfstype=ext4 rw rootwait earlycon=uart8250,mmio32,0xff178000,115200n8 keep_bootcon clk_ignore_unused pd_ignore_unused regulator_ignore_unused console=ttyS0,1500000n8 console=tty0 loglevel=7
